version: '3.7'

services:
  cstrike:
    container_name: cstrike
    image: fruworg/cstrike:1.0
    restart: unless-stopped
    volumes:
      - ./configs/motd.txt:/hlds/cstrike/motd.txt
      - ./configs/server.cfg:/hlds/cstrike/server.cfg
      - ./configs/config.cfg:/hlds/cstrike/config.cfg
      - ./configs/game.cfg:/hlds/cstrike/game.cfg
      - ./configs/game_init.cfg:/hlds/cstrike/game_init.cfg
      - ./configs/listip.cfg:/hlds/cstrike/listip.cfg
      - ./configs/banned.cfg:/hlds/cstrike/banned.cfg
      - ./configs/plugins.ini:/hlds/cstrike/addons/metamod/plugins.ini
    ports:
      - 27015:27015/udp
    env_file:
      - cstrike.env
