version: '3.7'

services:
  cstrike:
    container_name: cstrike
    image: fruworg/cstrike:latest
    restart: unless-stopped
    command: >
      ./hlds_run -game cstrike -strictportbind -ip 0.0.0.0 -port 27015
      +sv_lan 0 +map de_dust2 -maxplayers 16 +localinfo amxx_cfg cstrike/addons/amxmodx
    volumes:
      - ./configs/motd.txt:/hlds/cstrike/motd.txt
      - ./configs/server.cfg:/hlds/cstrike/server.cfg
      - ./configs/config.cfg:/hlds/cstrike/config.cfg
      - ./configs/game.cfg:/hlds/cstrike/game.cfg
      - ./configs/game_init.cfg:/hlds/cstrike/game_init.cfg
      - ./configs/listip.cfg:/hlds/cstrike/listip.cfg
      - ./configs/banned.cfg:/hlds/cstrike/banned.cfg
      - ./configs/plugins.ini:/hlds/cstrike/addons/metamod/plugins.ini
      - ./configs/amxx.cfg:/hlds/cstrike/addons/amxmodx/configs/amxx.cfg
      - ./configs/users.ini:/hlds/cstrike/addons/amxmodx/configs/users.ini
    ports:
      - 27015:27015/udp
